### ISSUE TITLE
Install and setup latest Bootstrap

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#22]
**Description**
Install and setup latest Bootstrap

#### Tasks
- [x] Install latest version of [Bootstrap](https://getbootstrap.com/)
    - [x] Install [`jquery@3.3.1`](https://www.npmjs.com/package/jquery) as Bootstrap ^v4.1.3 requires a peer dependency.
    - [x] Install [`popper.js@^1.14.3`](https://www.npmjs.com/package/popper.js) as Bootstrap ^v4.1.3 requires a peer dependency.
- [x] Import bootstrap `import 'bootstrap/dist/css/bootstrap.min.css';`

#### Install Bootstrap v4.1.3
```
npm install bootstrap
```
