### ISSUE TITLE
Apply favicon, Apple icons to React meta data

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#24]
**Description**
Apply favicon, Apple icons to React meta data

Tasks
- [x] Add favicon - Path `/public`
- [x] Upload `index.html` icons
- [x] Add `index.html` meta data – Path `/public/img/apple-touch-icons`
- [x] Upload `manifest.json` icons
- [x] Add `manifest.json` meta data

**Comment by guylepage3** [comment]
```
guylepage-bug-icon-rounded-48x48.png
guylepage-bug-icon-rounded-72x72.png
guylepage-bug-icon-rounded-96x96.png
guylepage-bug-icon-rounded-128x128.png
guylepage-bug-icon-rounded-256x256.png
guylepage-bug-icon-rounded.svg
```
