### ISSUE TITLE
Setup react router and react router dom

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#29]
#### Description
Setup react router and react router dom

#### Tasks
- [x] Install React Router DOM
- [x] Install React Router
- [x] Import the Router components needed into `index.js`
    - [x] `BrowserRouter`
    - [ ] ~~`Route`~~
    - [ ] ~~`Link`~~
- [x] Wrap `App.js` with `{BrowserRouter}`
- [x] Import to `App.js`
    - [x] `Routes`
    - [x] `Switch`
- [x] Add `Switch` and define routes and paths
- [x] Define 404 no match

**Comment by guylepage3** [comment]
Done
