### ISSUE TITLE
React Routing works in local machine but not Heroku

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#36]
**Description**
React Routing works in local machine but not Heroku and results in a 404 error nginx.

**Tasks**
Based on [Heroku Buildpack for create-react-app](https://elements.heroku.com/buildpacks/mars/create-react-app-buildpack) page under "Routing clean URLs."
- [x] Create new `static.json` file to clean urls and hold [custom routes](https://github.com/heroku/heroku-buildpack-static#custom-routes).
- [x] Add routing to `static.json` file https://github.com/guylepage3/lepage.cc/issues/36#issuecomment-429836465
- [x] Test direct urls.

**Reference**
Do a search for...
```
direct url 404 heroku react router
```
- [React Routing works in local machine but not Heroku](https://stackoverflow.com/questions/41772411/react-routing-works-in-local-machine-but-not-heroku)

**Comment by guylepage3** [comment]
You need to modify Heroku's default webpack, otherwise the service gets confused with how to handle the client-side routing. Essentially what static.json does. The rest is just the correct way to handle the routing according to the 'react-router' documentation.

**Comment by guylepage3** [comment]
Found full instructions on [Heroku Buildpack for create-react-app](https://elements.heroku.com/buildpacks/mars/create-react-app-buildpack) page under "Routing clean URLs."

**Comment by guylepage3** [comment]
Also see how to configure each custom route.. https://github.com/heroku/heroku-buildpack-static#custom-routes

**Comment by guylepage3** [comment]
```
{
  "root": "build/",
  "clean_urls": false,
  "routes": {
    "/**": "index.html"
  }
}
```

**Comment by guylepage3** [comment]
Done
