### ISSUE TITLE
lepage.cc v1.0.0 - Access a working web app

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#43]
**lepage.cc v1.0.0 - Access a working web app**
As I user, I want to be able to navigate to lepage.cc and be able to see the web app.

**Tasks**
- [x] guylepage3/lepage.cc#41 Update favicon, apple touch and website support images
- [x] guylepage3/lepage.cc#42 Add serviceWorker support for offline app capability
- [x] guylepage3/lepage.cc#39 Define grid values
- [x] guylepage3/lepage.cc#38 Enforce HTTPS-only via static.json
- [x] guylepage3/lepage.cc#36 React Routing works in local machine but not Heroku
- [x] guylepage3/lepage.cc#37 Update create react app to v2.0.5
- [x] guylepage3/lepage.cc#35 Redirect http to https
- [x] guylepage3/lepage.cc#34 Develop new Home content
- [x] guylepage3/lepage.cc#33 Add 5 second delay redirect to Intro component
- [x] guylepage3/lepage.cc#29 Setup react router and react router dom
- [x] guylepage3/lepage.cc#32 Add npm link to README.md
- [x] guylepage3/lepage.cc#31 Add contact link to footer
- [x] guylepage3/lepage.cc#30 Bug: Header logo not aligning correctly on mobile
- [x] guylepage3/lepage.cc#28 Live design content for landing view / animation
- [x] guylepage3/lepage.cc#21 Create new Google Cloud Storage Bucket
- [x] guylepage3/lepage.cc#25 Install package to analyze bundle size and code bloat
- [x] guylepage3/lepage.cc#24 Apply favicon, Apple icons to React meta data
- [x] guylepage3/lepage.cc#27 Apple touch icon and favicon production
- [x] guylepage3/lepage.cc#23 Setup Bootstrap Sass theming
- [x] guylepage3/lepage.cc#19 Create CircleCI script and setup notifications
- [x] guylepage3/lepage.cc#20 Set up Google Analytics
- [x] guylepage3/lepage.cc#5 Live design v1.0.0 website
- [x] guylepage3/lepage.cc#22 Install and setup latest Bootstrap
- [x] guylepage3/lepage.cc#18 Add node-sass
- [x] guylepage3/lepage.cc#26 Logo set v1.0.0 production
- [x] guylepage3/lepage.cc#14 Design Guy Lepage logo
- [x] guylepage3/lepage.cc#17 Create a free SSL certificate
- [x] guylepage3/lepage.cc#16 Setup domain and custom root domain
- [x] guylepage3/lepage.cc#2 lepage.cc v1.0 portfolio web app tasks
- [x] guylepage3/lepage.cc#15 Setup Create React App
- [x] guylepage3/lepage.cc#10 Choose stack for web app

**Comment by guylepage3** [comment]
Pushed first release https://github.com/guylepage3/lepage.cc/releases/tag/1.4.4
