### ISSUE TITLE
Finalize Bootstrap grid layout values

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#47]
**Description**
Finalize Bootstrap grid layout values

**Tasks**
- [x] Write out that the values are Bootstrap standard.
- [x] Write out the rules for the grid.
- [x] Refactor app to be Bootstrap semantic.
- [x] Restructure and add 1140px container width to Logo set illustrator file.

**Comment by guylepage3** [comment]
Done
