### ISSUE TITLE
Live design v1.0.0 website

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#5]
**Description**
Live design v1.0.0 of website

#### Tasks
- [x] Adjust project title in html and `manifest.json`
- [x] Add project description to html meta data
- [x] Full page cover wrapper
- [x] Create `Hero.js` component
  - [x] `h1`
  - [x] `lead`
- [x] Center hero content in window
- [x] Animate hero content
- [x] `Header.js` component
  - [x] `Image.js` component
  - [x] Add SVG logo
- [x] Create Google Forms contact form
- [ ] `Footer.js` component
