### ISSUE TITLE
Build new Header.js component

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#53]
**Description**
Build new Header.js component to implement new home page design https://github.com/guylepage3/lepage.cc/issues/50

Issues
- The header needs to remain on top of all content but not be a sticky header.
- Header needs to have no background until scroll below y `100px`.

**Tasks**
- [x] Rename and update old `Header.js` to `HeaderLight.js`
- [ ] Build `Header.js` component.
  - [ ] Build `Social.js` component.
  - [ ] Build navbar links.
- [ ] Build collapse sandwich menu for navigation on sm.
