### ISSUE TITLE
Build Hero.js component

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#54]
**Description**
Build new `Hero.js` component to implement new home page design https://github.com/guylepage3/lepage.cc/issues/50

**Tasks**
- [x] Build new component
- [x] Adjust background of app to be `#fff`
- [x] Adjust CSS animation on `Intro.js` to fade out background from `#000` to `#fff`.

**Comment by guylepage3** [comment]
Done.
