### ISSUE TITLE
Create design resource system

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#57]
**Description**
Ran into a major issue today when copying and pasting symbols over to another Sketch file. They were duplicating symbols. To solve this issue, I devised a design resource system that combines Sketch libraries with templates, etc.

Tasks
- [x] Define rules
- [ ] Create files
- [x] [#60 Define color system](https://github.com/guylepage3/lepage.cc/issues/60)
- [x] [#61 Define additional values to spacing rules](https://github.com/guylepage3/lepage.cc/issues/61)
- [x] [#62 Setup typography testing environment](https://github.com/guylepage3/lepage.cc/issues/62)
- [x] [#58 Define typography](https://github.com/guylepage3/lepage.cc/issues/58)

**Reference**
https://developer.apple.com/design/resources/

**Comment by guylepage3** [comment]
Apple > Developer > Human Interface Guidelines > Apple Design Resources

[Apple Developer Apple Design Resources.pdf](https://github.com/guylepage3/lepage.cc/files/2526390/Apple.Developer.Apple.Design.Resources.pdf)

![apple developer apple design resources](https://user-images.githubusercontent.com/1711854/47669028-500b1300-db80-11e8-8d8e-09394c7f239a.png)

**Comment by guylepage3** [comment]
Using http://github.com/universelabs/meta. Closing issue.
