### ISSUE TITLE
Build new Footer.js component

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#68]
**Description**
Build new `Footer.js` component to implement new home page design https://github.com/guylepage3/lepage.cc/issues/50

**Tasks**
- [x] Build new component
- [x] Build col component
- [x] Social component
- [x] Copyright component
- [x] Subscribe button
- [x] Adjust layouts for mobile & desktop

**Comment by guylepage3** [comment]
Done
