### ISSUE TITLE
Create Newsletter API, subscribe form, errors and emails

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#69]
**Description**
Create Newsletter API, subscribe form, errors and emails

**Tasks**
- [x] Build Subscribe component
- [x] Build Error component
- [x] Build Success component
- [x] Build Node/Express server
- [x] Build API
- [x] Build `dev` & `production` environment to hide keys
- [x] Test
- [x] Design and build Mailchimp email forms
- [x] Adjust layouts for mobile & desktop

**Comment by guylepage3** [comment]
Done
