### ISSUE TITLE
Computer Setup

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/lepage.cc#77]
**Description**
New computer setup checklist

Reference: [#214 New computer setup checklist](https://github.com/guylepage3/personal/issues/214)

[Nov 18, 2018]
**NEW!** Read through Medium post setup.. [Your new ReactJS on Sublime Text 3 workspace setup](https://medium.com/@dwardmr/your-new-reactjs-on-sublime-text-3-workspace-setup-9ce87c12e93a)

**Tasks**
- [x] Dropbox (! -------- Make sure you start this first. It takes a while to sync ------- !)
- [x] Mac menu bar
- [x] Users
- [x] `.bash_profile` scripts - [bash_profile.zip](https://github.com/guylepage3/personal/files/2679949/bash_profile.zip)
- [x] System preferences - Keyboard > Text > Uncheck "Add period with doublespace"
- [x] Folder settings
- [x] Folder settings - [Open trash/items in tabs](https://www.designernews.co/stories/74520-tabs-in-sketch-with-macos-sierra)
    - This also allows `Sketch` to open in tabs.
- [x] Fonts - * Sublime Text
    - Inconsolata (Google font).
- [x] Fonts - * Clppr
    - Lato (Google font).
- [x] Fonts - * Lepage.cc
    - SF Pro Display (Apple font).
    - SF Pro Text (Apple font).
    - Source Code Pro (Google font).
    - Font Awesome 5 Brands (FortAwesome font).
    - Font Awesome 5 Free (FortAwesome font).
- [x] Fonts - * Papriika
    - Univers (Adobe font).
    - Univers LT Std (Adobe font).
- [x] Fonts - * Universe
    - SF Pro Display (Apple font).
    - SF Pro Text (Apple font).
    - Maven Pro (Google font)(Universe Logo).
    - Source Code Pro (Google font).
    - Font Awesome 5 Brands (FortAwesome font).
    - Font Awesome 5 Free (FortAwesome font).
- [x] Applications - Install [Duet Display](https://www.duetdisplay.com/)
- [x] Applications - Install [Adobe Creative Cloud](https://www.adobe.com/creativecloud.html)
- [ ] Applications - Adobe Creative Suite - Preferences / Workspaces
- [x] Applications - Install [Spotify](https://www.spotify.com/)
- [ ] Applications - Export Sketch Palettes
- [x] Applications - Install [Sketch](https://www.sketchapp.com/)
- [x] Applications - Sketch - Preferences - [Open all windows in tabs](https://www.designernews.co/stories/74520-tabs-in-sketch-with-macos-sierra)
    - This also allows `Trash` to open in tabs.
- [x] Applications - Sketch - Preferences - Install [Rename It](https://rodi01.github.io/RenameIt/)
- [x] Applications - Sketch - Preferences - Install [Sketch Palettes](https://github.com/andrewfiorillo/sketch-palettes)
- [x] Applications - Sketch - Preferences - Install [Sketch Find And Replace](https://github.com/thierryc/Sketch-Find-And-Replace)
- [x] Applications - Sketch - Preferences - Install [Craft](https://www.invisionapp.com/lp/download-craft/)
- [x] Applications - Install Xcode - Xcode is required for Git and bash updates.
- [x] Applications - Terminal - Install [GIt](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
- [x] Applications - Terminal - [Update Git to latest version](https://git-scm.com/download/mac)
- [x] Applications - Terminal - Preferences - Import Terminal preferences.
    - Terminal preferences > Import > [Electric.terminal.zip](https://github.com/guylepage3/personal/files/2648900/Electric.terminal.zip)
- [x] Applications - Install [Brew](https://brew.sh/)
- [x] Applications - Install [Node.js](https://nodejs.org/en/)
- [x] Applications - [npm update](https://www.npmjs.com/get-npm)
  - Permissions issue - [Need to resolve issue with permissions](https://github.com/guylepage3/personal/issues/495#issuecomment-444560308)
- [x] Applications - Install [Autodesk](https://www.autodesk.com/)
- [x] Applications - Install [Framer X](https://framer.com/)
- [x] Applications - Install [Atom](https://atom.io/)
- [x] Applications - Install [Sublime Text 3](https://www.sublimetext.com/3)
- [x] Applications - Sublime Text 3 – [Preferences](https://github.com/guylepage3/personal/issues/495#issuecomment-444527361)
- [x] Applications - Install [GPG Suite](https://gpgtools.org/).
- [x] Applications - GitHub - Review SSH and GPG keys.
  - [x] ! ----- DO NOT DELETE ANY GPG KEYS ON GITHUB ----- !
  - [x] It is ok to remove SSH keys no longer needed.
- [x] Applications - GitHub – [Generating a new SSH key](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) #500
  - [x] Applications - GitHub – [Adding SSH key to SSH agent](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent). You'll need to create a `~/.ssh/config` file.
- [x] Applications - GitHub – [Adding a new SSH key to your GitHub account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)
- [x] Applications - GPG Suite - Export and import GPG Keys.
  - Check "Include secret key in exported file" when exporting.
- [x] Applications - GitHub - Setup commit signing. [Checklist - GPG commit signature verification](https://help.github.com/articles/about-commit-signature-verification/#gpg-commit-signature-verification)
  - [x] [Check for existing GPG keys](https://help.github.com/articles/checking-for-existing-gpg-keys/)
  - [x] [Tell Git about your signing key](https://help.github.com/articles/telling-git-about-your-signing-key/)
  - [x] [Set your commit email address in Git](https://help.github.com/articles/setting-your-commit-email-address-in-git/) & [author name](https://git-scm.com/docs/git-config#git-config-username).
    - `git config --global user.email "guylepage3@gmail.com"`
    - `git config --global user.name "Guy Lepage"`
  - [x] Important: [Configure your Git client to sign commits in any local repository on your computer.](https://help.github.com/articles/signing-commits/) See "Tips."
    - `git config --global commit.gpgsign true`
  - [x] Test commit signing by executing a commit.
- [x] Copy all repositories from [old `~/sites` directory](https://github.com/guylepage3/personal/issues/495#issuecomment-445233100) to new `~/sites` directory.
- [x] Applications - Install [Jaxx](https://jaxx.io/)
- [x] Applications - Install [Robo 3T](https://robomongo.org)
- [x] Applications - Install [Postman](https://www.getpostman.com/)
- [x] Applications - Install MongoDB - https://treehouse.github.io/installation-guides/mac/mongo-mac.html
- [x] Applications - MongoDB Compass
- [x] Applications - Pixave install
- [x] Applications - Pixave - Open Pixave > Preferences > Library, move empty `Pixave.pxvlibrary` into `guy/Dropbox/`, then drag, drop, replace with old `Pixave.pxvlibrary`. Then Open Pixave > Preferences > Library, move `Pixave.pxvlibrary` to `guy/apps/`.
- [x] Copy `Pictures` directory onto external HD, open Photos.app, Close app, copy folder contents into new `Pictures` directory and replace `Photos Library.photoslibrary`.

[NEXT ›› #496 Organize and update backups, archive, passwords, recovery, etc.](https://github.com/guylepage3/personal/issues/496)
